config/routes.rb
Notes::Application.routes.draw do

  post "/sessions", to: "application#create_session"
  get "/login", to: "application#login"
  get "/logout", to: "application#destroy_session"

  root to: "notes#index"
  get "/autocomplete", to: "notes#autocomplete"
  get "/tags/autocomplete", to: "tags#autocomplete"

  resources :notes do
    collection do
      get "filter"
      get "browse"

      get "tune_widget"
    end
  end

  resources :documents, only: [:show]
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id            :integer          not null, primary key
#  title         :string(255)
#  body          :text
#  date          :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  original_date :datetime
#  user_id       :integer          not null
#

class Note < ActiveRecord::Base
  attr_accessible :body, :date, :public, :title, :tag_list

  belongs_to :user

  include Note::Versions
  include Note::Tags
  include Note::Attachments
  include Note::Json
  include Note::Content
end

app/models/note/attachments.rb
class Note
  module Attachments
    extend ActiveSupport::Concern

    included do
      has_many :attachments, :dependent => :destroy
      accepts_nested_attributes_for :attachments
      attr_accessible :attachments_attributes
    end
  end
end

app/models/note/content.rb
class Note
  module Content
    extend ActiveSupport::Concern

    included do
      before_validation :fix_html
    end

    def preview(maxlen=40)
      preview = (title.blank? ? body : title).strip_tags.strip

      preview = preview.gsub(/&#(\d+);/){ |x| x[/\d+/].to_i.chr }
      preview = preview.gsub(/&\w+;/, '')
      preview = preview.size > 45 ? "#{preview[0,45]}..." : "#{preview}"
      lines = preview.split(/\n+/, 2)

      if lines.length > 1
        "#{lines.first.sub(/\W+$/, '')}..."
      else
        lines.first
      end
    end

    def outline
      doc = Nokogiri::HTML(body){ |config| config.nonet }

      outline = Outline.new
      doc.css("h1, h2, h3, h4, h5, h6, h7").each do |node|
        if !outline.parent || outline.level < node.name
          outline = outline.child(node.text, node.name)
        else
          while outline.parent && node.name <= outline.level
            outline = outline.parent
          end

          outline = outline.child(node.text, node.name)
        end

        outline.anchor = node.attribute("id").try(:value)
      end

      outline = outline.parent while outline.parent
      outline
    end

    private

    include ActionView::Helpers::TextHelper

    def fix_html
      sanitizer = Rails::Html::WhiteListSanitizer.new

      # abc notes uses class="abc"
      tags = [*"h1".."h7", "p", "ol", "ul", "li", "br", "hr",
              "blockquote", "pre", "table", "thead", "tbody", "tr", "th", "td",
              "a", "b", "strong", "i", "em", "u", "code"]
      body = sanitizer.sanitize(self.body, tags: tags, attributes: %w(class href))

      body = auto_link(body, link: :urls)

      doc = Nokogiri::HTML::DocumentFragment.parse(body)

      doc.css("table").each do |node|
        node.set_attribute("class", "table")
      end

      doc.css("h1, h2, h3, h4, h5, h6, h7").each_with_index do |node, inode|
        id = node.text.gsub(/\s+/, "-") + "-#{inode}"
        node.set_attribute("id", id.downcase)
      end

      doc.css("a").each do |node|
        node.set_attribute("target", "_blank")
      end

      self.body = doc.to_s
    end

    class Outline
      attr_accessor :parent, :title, :anchor, :level, :children

      def initialize
        @children = []
      end

      def child(title, level)
        Outline.new.tap do |child|
          child.parent = self
          child.title = title
          child.level = level
          children << child
        end
      end

      def to_s
        if parent
          ["- " * level[/\d+/].to_i + title,
           *children.map(&:to_s)].join("\n")
        else
          children.map(&:to_s).join("\n")
        end
      end

      def to_h
        if parent
          { title: title, anchor: anchor, children: children.map(&:to_h) }
        else
          children.map(&:to_h)
        end
      end
    end
  end
end

app/models/note/json.rb
class Note
  module Json
    def as_json(opts=nil)
      opts ||= {
        :only => [:id, :original_date],
        :include => {
          :tags => {
            :only => [], :methods => :short_label
          },
        },
        :methods => :preview
      }

      super(opts)
    end
  end
end

app/models/note/tags.rb
class Note
  module Tags
    extend ActiveSupport::Concern

    included do
      has_many :tags, :dependent => :destroy

      scope :tagged, ->(tag) {
        where("tags.label = ? OR tags.label LIKE ?", tag, "#{tag}:%")
      }
    end

    def tag_list
      tags.map(&:label).join(', ')
    end

    def tag_list=(list)
      list = list.split(/\s*,\s*/)
      self.tags = list.map{ |label| tags.build(:label => label) }
    end

    def tagged?(label)
      tags.map(&:label).include?(label)
    end
  end
end

app/models/note/versions.rb
class Note
  module Versions
    extend ActiveSupport::Concern

    included do
      has_many :versions, class_name: 'NoteVersion'

      after_find :build_version
      before_update :save_version
      before_save :save_original_date
    end

    def save_version!
      @version.try(:save!)
    end

    private

    def build_version
      params = { title: title, body: body, date: date, note_id: id }
      @version = NoteVersion.new(params, without_protection: true)
    end

    def save_version
      @version.try(:save!) if title_changed? || body_changed?
    end

    def save_original_date
      self.original_date ||= date
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  helper_method :filter_results

  def index
    respond_to do |format|
      format.html do
        render layout: (request.xhr? ? nil : "browser")
      end
      format.json do
        render json: { results: filter_results,
                       tags: tags_scope.labels,
                       saved_filters: SavedFilter.all }
      end
    end
  end

  def show
    @note = notes_scope.find(params[:id])
    render layout: (request.xhr? ? nil : "browser")
  end

  def edit
    @note = notes_scope.find(params[:id])
    render layout: (request.xhr? ? nil : "browser")
  end

  def new
    @note = notes_scope.new
    render layout: (request.xhr? ? nil : "browser")
  end

  def create
    params[:note][:date] = Time.utc(*params[:note][:date].split('/').map(&:to_i))

    @note = current_user.notes.new(params[:note])

    if @note.save
      respond_to do |format|
        format.html{ redirect_to note_path(@note, f: params[:f]) }
        format.json do
          item = @note.as_json
          item["url"] = note_path(@note, f: params[:f])
          render json: item
        end
      end
    else
      render :json => @note.errors,  :status => :unprocessable_entity
    end
  end

  def update
    @note = current_user.notes.find(params[:id])
    if @note.update_attributes(params[:note])
      respond_to do |format|
        format.html{ redirect_to note_path(@note, f: params[:f]) }
        format.json do
          item = @note.as_json
          item["url"] = note_path(@note, f: params[:f])
          render json: item
        end
      end
    else
      render :json => @note.errors,  :status => :unprocessable_entity
    end
  end

  def destroy
    @note = current_user.notes.find(params[:id])
    @note.transaction do
      @note.save_version!
      @note.destroy
    end
    render json: { :success => true }
  end

  def autocomplete
    term = params[:term]
    if term[0] == '.'
      matches = tags_scope.autocomplete(term[1..-1]).map do |tag|
        {:label => '.'+tag, :value => '.'+tag}
      end
    else
      notes = notes_scope.where('lower(notes.title) LIKE ?', "%#{params[:term].downcase}%")
      matches = notes.pluck(:title).uniq.sort.map do |title|
        {:label => title, :value => title.inspect}
      end
    end
    render :json => matches.flatten
  end

  def tune_widget
    render :layout => 'basic'
  end

  private

  def filter_results
    @filter_results ||=
      begin
        results = Filter.new(params[:f], user: current_user).notes.as_json(
          only: :id, methods: :preview,
          include: {
            tags: { only: :id, methods: :short_label }
          }
        )
        results.each do|item|
          item["url"] = note_path(item["id"], f: params[:f])
          item["id"] = "notes/#{item['id']}"
        end
      end
  end

  def notes_scope
    if logged_in?
      Note.where("notes.user_id = ? OR notes.public = ?", current_user.id, true)
    else
      Note.where(public: true)
    end
  end

  def tags_scope
    if logged_in?
      Tag.joins(:note).where("notes.public = ? OR notes.user_id = ?",
                             true, current_user.id)
    else
      Tag.joins(:note).where(notes: { public: true })
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def tag_link(base_url, tag)
    links = '<span class="tag-links">'
    tag.split(':').inject('') do |prefix, part|
      tag = (prefix.blank? ? '' : prefix+':') + part
      links << (prefix.blank? ? '' : ':')
      links << link_to(part, base_url+tag, 'data-tag' => tag)
      tag
    end
    (links << '</span>').html_safe
  end

  def tag_selector_button(note, tag)
    css_class = 'btn btn-default btn-sm'
    css_class << ' active' if note.tagged?(tag)
    content_tag(:span, :class => css_class,
                :"data-toggle" => 'button'){ tag }
  end
end

app/views/notes/_form.html.erb
<div class="note edit">
  <%= form_for(note) do |f| %>
    <%= f.hidden_field :date %>

    <div class="title">
      <%= f.text_field :title, "class": "form-control", autocomplete: "off",
          placeholder: f.object.persisted? ? "Add a title" : "A new note" %>
    </div>

    <div class="body editor">
      <%= f.text_area :body, "class": "form-control" %>
    </div>

    <div class="tags">
      <div class="input-group">
        <div class="input-group-btn">
          <div class="btn btn-default" data-toggle="modal"
               data-target="form:visible .tag-selector">Tags</div>
        </div>

        <%= f.text_field :tag_list, "class": "form-control", autocomplete: "off",
            placeholder: "Add tags (separate with commas)" %>

        <div class="input-group-btn">
          <input type="submit" value="Save" class="btn btn-default btn-success" />
        </div>
      </div>
    </div>

    <div class="modal tag-selector" tabindex="-1">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header"><h3>Tags</h3></div>
          <div class="modal-body">
            <% current_user.tags.labels.each do |tag| %>
              <%= tag_selector_button(note, tag) %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <%= actions do %>
    <% if note.persisted? %>
      <a href="<%= note_path(note, f: params[:f]) %>" title="Discard changes"
         class="fa fa-remove" data-edit-action="true"></a>
    <% else %>
      <a href="<%= notes_path(f: params[:f]) %>" title="Discard changes"
         class="fa fa-remove" data-edit-action="true"></a>
    <% end %>
  <% end %>
</div>

app/views/notes/_note.html.erb
<div class="note">
  <h1 class="title"><%= note.title %></h1>

  <div class="body">
    <%= sanitize note.body %>
  </div>

  <footer>
    <div class="tags">
      <% note.tags.map(&:label).each do |tag| %>
        <%= tag_link(url_for(f: '.'), tag) %>
      <% end %>
    </div>
  </footer>

  <%= actions(note.user == current_user) do %>
    <a href="<%= edit_note_path(note, f: params[:f]) %>" title="Edit this item"
       class="fa fa-pencil" data-edit-action="true"></a>

    <%= form_for(note, html: { id: "toggle_published_note_#{note.id}" }) do |f| %>
      <%= hidden_field_tag :f, params[:f] %>
      <%= f.hidden_field :public, value: !note.public? %>
      <button type="submit" form="<%= f.options[:html][:id] %>" title="<%= note.public ? "Un-publish" : "Publish" %> this note">
        <span class="fa fa-eye<%= "-slash" if note.public? %>"></span>
      </button>
    <% end %>
  <% end %>
</div>

app/views/notes/edit.html.erb
<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<script type="text/javascript">
  $(document).ready(function() { $("#browser").show() });
</script>

<%= actions %>

app/views/notes/new.html.erb
<%= render "form", note: @note %>

app/views/notes/show.html.erb
<%= render @note %>

app/views/notes/tune_widget.html.erb
<center>
  <div class="tune_widget" style="margin-top: 25px">
  </div>
</center>