config/routes.rb
Notes::Application.routes.draw do

  post "/sessions", to: "application#create_session"
  get "/login", to: "application#login"
  get "/logout", to: "application#destroy_session"

  root to: "notes#index"
  get "/autocomplete", to: "notes#autocomplete"
  get "/tags/autocomplete", to: "tags#autocomplete"

  resources :notes do
    collection do
      get "filter"
      get "browse"

      get "tune_widget"
    end
  end

  resources :documents, only: [:show]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_current_user, :except => :login

  attr_reader :current_user
  helper_method :current_user, :logged_in?

  def login
    render "login", layout: "logged_out", locals: { user: User.new }
    return false
  end

  def create_session
    user = User.find_by(login_name: params[:user][:login_name])
    if user.try(:verify, params[:user][:password])
      session[:user_id] = user.id
      redirect_to "/"
    else
      user ||= User.new(login_name: params[:user][:login_name])
      user.errors.add("user name or password", "is incorrect")
      render "login", layout: "logged_out", locals: { user: user }
    end
  end

  def destroy_session
    session[:user_id] = nil
    redirect_to '/'
  end

  protected

  def set_current_user
    unless session[:user_id].blank?
      @current_user = User.find(session[:user_id])
    end
  end

  def logged_in?
    current_user.presence
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user
  end

  def actions(cond=true, &block)
    item_actions = capture(&block) if cond && block_given?
    item_actions = item_actions.presence.try(:+, content_tag(:hr))

    actions = []
    actions << content_tag(:div, "class": "navigate") do
      content = content_tag(:div, id: "item_actions"){ item_actions }
      content << content_tag(:a, "", "href": "#browser",
                                     "class": "fa fa-search",
                                     "data-search-action": true,
                                     "title": "Search notes")
      content << content_tag(:a, "", "href": new_note_path(f: params[:f]),
                                     "class": "fa fa-plus",
                                     "data-new-action": true,
                                     "title": "Create a note") if logged_in?
      content << content_tag(:hr)
    end

    actions << content_tag(:span, "", "class": "fa fa-user",
                                      "title": "Your account")
    if logged_in?
      actions << content_tag(:a, "", "href": "/settings",
                                     "class": "fa fa-cog",
                                     "title": "Settings")
      actions << content_tag(:a, "", "href": logout_path,
                                     "class": "fa fa-sign-out",
                                     "title": "Log out",
                                     "data-logout": true)
    else
      actions << content_tag(:a, "", "href": login_path,
                             "title": "Log in",
                             "class": "fa fa-sign-in")
    end

    content_tag(:div, class: "browser-app-actions"){ actions.join.html_safe }
  end

  def tag_labels
    if logged_in?
      Tag.joins(:note).where("notes.public = ? OR notes.user_id = ?",
                             true, current_user.id).labels
    else
      Tag.joins(:note).where(notes: { public: true }).labels
    end
  end
end

app/views/application/login.html.erb
<%= form_for(user, url: sessions_path, method: "post", html: { "class": "form-horizontal" }) do |f| %>
  <% if user.errors.any? %>
    <ul>
    <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>

  <%= f.text_field :login_name, placeholder: "Username", "class": "input-xxlarge", autofocus: user.login_name.blank? %>

  <%= f.password_field :password, placeholder: "Password", "class": "input-xxlarge", autofocus: user.login_name.present?  %>

  <%= f.submit "Log In" %>
<% end %>

app/views/application/welcome.html.erb
<%= form_for(user, url: login_path, method: "post", html: { "class": "form-horizontal" }) do |f| %>
  <% if user.errors.any? %>
    <ul>
    <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>

  <%= f.text_field :login_name, placeholder: "Username", "class": "input-xxlarge", autofocus: user.login_name.blank? %>

  <%= f.password_field :password, placeholder: "Password", "class": "input-xxlarge", autofocus: user.login_name.present?  %>

  <%= f.submit "Log In" %>
<% end %>